services:
- type: web
  name: n8n-content-engine            # edit if you want a different name
  env: docker
  plan: starter
  autoDeploy: true
  disk:
    name: n8n-data
    mountPath: /data
    sizeGB: 10
  envVars:
  - key: N8N_ENCRYPTION_KEY
    generateValue: true
  - key: N8N_PROTOCOL
    value: https
  - key: N8N_PORT
    value: $PORT
  - key: N8N_HOST
    value: n8n-content-engine.onrender.com        # set to match service name
  - key: N8N_EDITOR_BASE_URL
    value: https://n8n-content-engine.onrender.com/
  - key: WEBHOOK_URL
    value: https://n8n-content-engine.onrender.com/
  - key: GENERIC_TIMEZONE
    value: Australia/Sydney
  - key: N8N_BASIC_AUTH_ACTIVE
    value: "true"
  - key: N8N_BASIC_AUTH_USER
    value: admin                                   # set
  - key: N8N_BASIC_AUTH_PASSWORD
    value: cd67czS6SBUkeG2                            # set
  - key: N8N_DEFAULT_BINARY_DATA_MODE
    value: filesystem
  - key: AZURE_SPEECH_REGION
    value: australiaeast
  # Add these **in the Render dashboard after first deploy** (do not commit secrets):
  # - AZURE_SPEECH_KEY
  # - PEXELS_API_KEY
  # Optional hardening:
  # - N8N_DIAGNOSTICS_ENABLED=false
  # - N8N_PERSONALIZATION_ENABLED=false
